"""adding missing columns

Revision ID: 070927b8e23a
Revises: 832f19b0c2c1
Create Date: 2025-08-18 17:22:04.654608

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "070927b8e23a"
down_revision: Union[str, Sequence[str], None] = "832f19b0c2c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit_request",
        "idempotency_id",
        new_column_name="idempotency_guid",
        schema="credit_manager",
    )
    op.alter_column(
        "financial_transaction",
        "idempotency_id",
        new_column_name="idempotency_guid",
        schema="credit_manager",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit_request",
        "idempotency_guid",
        new_column_name="idempotency_id",
        schema="credit_manager",
    )
    op.alter_column(
        "financial_transaction",
        "idempotency_guid",
        new_column_name="idempotency_id",
        schema="credit_manager",
    )
    # ### end Alembic commands ###
