"""adding missing columns

Revision ID: 0a117f64bcd7
Revises: ac6085ec791d
Create Date: 2025-08-18 15:53:14.194871

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a117f64bcd7"
down_revision: Union[str, Sequence[str], None] = "ac6085ec791d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credit_request",
        sa.Column("income", sa.DECIMAL(precision=14, scale=2), nullable=False),
        schema="credit_manager",
    )
    op.add_column(
        "credit_request",
        sa.Column("reason", sa.String(length=255), nullable=False),
        schema="credit_manager",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit_request", "reason", schema="credit_manager")
    op.drop_column("credit_request", "income", schema="credit_manager")
    # ### end Alembic commands ###
