"""adding missing columns

Revision ID: 832f19b0c2c1
Revises: 0a117f64bcd7
Create Date: 2025-08-18 17:20:57.742752

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "832f19b0c2c1"
down_revision: Union[str, Sequence[str], None] = "0a117f64bcd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credit_request",
        sa.Column("webhook_url", sa.String(length=255), nullable=False),
        schema="credit_manager",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit_request", "webhook_url", schema="credit_manager")
    # ### end Alembic commands ###
