"""adding created_at field

Revision ID: 9a71cde2d308
Revises: b6c673fd973f
Create Date: 2025-08-18 17:58:24.216100

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a71cde2d308"
down_revision: Union[str, Sequence[str], None] = "b6c673fd973f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credit_request",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        schema="credit_manager",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit_request", "created_at", schema="credit_manager")
    # ### end Alembic commands ###
