"""add indexes

Revision ID: a0cfe2edae80
Revises: 9a71cde2d308
Create Date: 2025-08-19 18:33:14.847572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0cfe2edae80'
down_revision: Union[str, Sequence[str], None] = '9a71cde2d308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credit_manager_credit_request_idempotency_guid'), 'credit_request', ['idempotency_guid'], unique=False, schema='credit_manager')
    op.create_index(op.f('ix_credit_manager_credit_request_profile_guid'), 'credit_request', ['profile_guid'], unique=False, schema='credit_manager')
    op.create_index(op.f('ix_credit_manager_financial_transaction_idempotency_guid'), 'financial_transaction', ['idempotency_guid'], unique=False, schema='credit_manager')
    op.create_index(op.f('ix_credit_manager_financial_transaction_profile_guid'), 'financial_transaction', ['profile_guid'], unique=False, schema='credit_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_manager_financial_transaction_profile_guid'), table_name='financial_transaction', schema='credit_manager')
    op.drop_index(op.f('ix_credit_manager_financial_transaction_idempotency_guid'), table_name='financial_transaction', schema='credit_manager')
    op.drop_index(op.f('ix_credit_manager_credit_request_profile_guid'), table_name='credit_request', schema='credit_manager')
    op.drop_index(op.f('ix_credit_manager_credit_request_idempotency_guid'), table_name='credit_request', schema='credit_manager')
    # ### end Alembic commands ###
