"""initial rev

Revision ID: ac6085ec791d
Revises: 
Create Date: 2025-08-18 15:38:59.026849

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac6085ec791d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_request",
        sa.Column(
            "guid",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("idempotency_id", sa.Uuid(), nullable=False),
        sa.Column("profile_guid", sa.Uuid(), nullable=False),
        sa.Column(
            "requested_amount", sa.DECIMAL(precision=14, scale=2), nullable=False
        ),
        sa.Column("requested_credit_type", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column(
            "available_amount", sa.DECIMAL(precision=14, scale=2), nullable=False
        ),
        sa.Column("available_credit_type", sa.String(length=255), nullable=False),
        sa.Column("interest_rate", sa.DECIMAL(precision=8, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("guid"),
        schema="credit_manager",
    )
    op.create_table(
        "financial_transaction",
        sa.Column(
            "guid",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("profile_guid", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=14, scale=2), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("due_at", sa.DateTime(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("idempotency_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("guid"),
        schema="credit_manager",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("financial_transaction", schema="credit_manager")
    op.drop_table("credit_request", schema="credit_manager")
    # ### end Alembic commands ###
