"""adding missing columns

Revision ID: b6c673fd973f
Revises: 070927b8e23a
Create Date: 2025-08-18 17:24:27.407373

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6c673fd973f"
down_revision: Union[str, Sequence[str], None] = "070927b8e23a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit_request",
        "available_amount",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        nullable=True,
        schema="credit_manager",
    )
    op.alter_column(
        "credit_request",
        "available_credit_type",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
        schema="credit_manager",
    )
    op.alter_column(
        "credit_request",
        "interest_rate",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        nullable=True,
        schema="credit_manager",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit_request",
        "interest_rate",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        nullable=False,
        schema="credit_manager",
    )
    op.alter_column(
        "credit_request",
        "available_credit_type",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
        schema="credit_manager",
    )
    op.alter_column(
        "credit_request",
        "available_amount",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        nullable=False,
        schema="credit_manager",
    )
    # ### end Alembic commands ###
