version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - uvicorn 
      - api:app 
      - --host 
      - "0.0.0.0" 
      - --port 
      - "80"
    env_file:
      - .env
    volumes:
      - .:/code
    healthcheck:
      test: python health_check.py --service api|| exit 1
      interval: 5s
      timeout: 5s
      retries: 5