"""remove unused colum

Revision ID: 34f8e6c0b1e2
Revises: 8a8fb46b1e98
Create Date: 2025-08-18 00:17:02.093437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34f8e6c0b1e2'
down_revision: Union[str, Sequence[str], None] = '8a8fb46b1e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emotion', 'received_at', schema='emotion_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotion', sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='emotion_processor')
    # ### end Alembic commands ###
