"""initial rev

Revision ID: 8a8fb46b1e98
Revises:
Create Date: 2025-08-18 00:12:50.991923

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a8fb46b1e98"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema if not exists emotion_processor")
    op.create_table(
        "emotion_trace",
        sa.Column(
            "guid",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("idempotency_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("guid"),
        schema="emotion_processor",
    )
    op.create_table(
        "emotion",
        sa.Column(
            "guid",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("trace_guid", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("percent", sa.Float(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trace_guid"],
            ["emotion_processor.emotion_trace.guid"],
        ),
        sa.PrimaryKeyConstraint("guid"),
        schema="emotion_processor",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("emotion", schema="emotion_processor")
    op.drop_table("emotion_trace", schema="emotion_processor")
    op.execute("drop schema emotion_processor")
    # ### end Alembic commands ###
