"""add indexes

Revision ID: ca90c9848ac7
Revises: 34f8e6c0b1e2
Create Date: 2025-08-19 18:34:17.505290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca90c9848ac7'
down_revision: Union[str, Sequence[str], None] = '34f8e6c0b1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_emotion_processor_emotion_trace_guid'), 'emotion', ['trace_guid'], unique=False, schema='emotion_processor')
    op.create_index(op.f('ix_emotion_processor_emotion_trace_idempotency_guid'), 'emotion_trace', ['idempotency_guid'], unique=False, schema='emotion_processor')
    op.create_index(op.f('ix_emotion_processor_emotion_trace_profile_guid'), 'emotion_trace', ['profile_guid'], unique=False, schema='emotion_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotion_processor_emotion_trace_profile_guid'), table_name='emotion_trace', schema='emotion_processor')
    op.drop_index(op.f('ix_emotion_processor_emotion_trace_idempotency_guid'), table_name='emotion_trace', schema='emotion_processor')
    op.drop_index(op.f('ix_emotion_processor_emotion_trace_guid'), table_name='emotion', schema='emotion_processor')
    # ### end Alembic commands ###
