"""fixing columns names

Revision ID: d3fbbf039598
Revises: 34f8e6c0b1e2
Create Date: 2025-08-18 13:15:36.301984

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3fbbf039598"
down_revision: Union[str, Sequence[str], None] = "34f8e6c0b1e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "emotion_trace",
        "profile_id",
        new_column_name="profile_guid",
        schema="emotion_processor",
    )
    op.alter_column(
        "emotion",
        "profile_id",
        new_column_name="profile_guid",
        schema="emotion_processor",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "emotion",
        "profile_guid",
        new_column_name="profile_id",
        schema="emotion_processor",
    )
    op.alter_column(
        "emotion_trace",
        "profile_guid",
        new_column_name="profile_id",
        schema="emotion_processor",
    )
    # ### end Alembic commands ###
