"""add indexes

Revision ID: 0e0680d62df6
Revises: c7d9212fa2a9
Create Date: 2025-08-19 18:45:31.358576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0680d62df6'
down_revision: Union[str, Sequence[str], None] = 'c7d9212fa2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_public_gateway_user_api_key'), 'user', ['api_key'], unique=False, schema='public_gateway')
    op.create_index(op.f('ix_public_gateway_user_metadata_user_guid'), 'user_metadata', ['user_guid'], unique=False, schema='public_gateway')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_gateway_user_metadata_user_guid'), table_name='user_metadata', schema='public_gateway')
    op.drop_index(op.f('ix_public_gateway_user_api_key'), table_name='user', schema='public_gateway')
    # ### end Alembic commands ###
