"""initial rev

Revision ID: c7d9212fa2a9
Revises:
Create Date: 2025-08-18 20:19:24.021526

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7d9212fa2a9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "guid",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("registered_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("guid"),
        sa.UniqueConstraint("email"),
        schema="public_gateway",
    )
    op.create_table(
        "user_metadata",
        sa.Column(
            "guid",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_guid", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_guid"],
            ["public_gateway.user.guid"],
        ),
        sa.PrimaryKeyConstraint("guid"),
        schema="public_gateway",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_metadata", schema="public_gateway")
    op.drop_table("user", schema="public_gateway")
    # ### end Alembic commands ###
